export * from "./types.js";
export { OCCUPANCY_LOAD_TABLE, FIXED_SEATS_RULE, CONTINUOUS_BENCH_ROW_RULE, ESTUDIO_EVACUACION_THRESHOLD_PERSONS } from "./dictionary/occupancyLoad.js";
export { STAIRS_TABLE, STAIRS_STUDY_REQUIRED_ABOVE_PERSONS, lookupStairsRequirement } from "./dictionary/stairs.js";
export * as evacuationRouteConstants from "./dictionary/evacuationRoutes.js";
export { STARTER_SYNONYMS } from "./dictionary/synonyms.js";
export { matchDestino } from "./engine/matchDestino.js";
export { calculateOccupancyLoad } from "./engine/calculateOccupancyLoad.js";
export { evaluateStairs } from "./engine/evaluateStairs.js";
export { evaluateEvacuationRoutes, evaluateHeightRule, evaluateWidthRule, evaluateTerraceRule } from "./engine/evaluateEvacuationRoutes.js";
export { validateStairs, measureStairWidthM } from "./engine/stairValidation.js";
export { STAIRS_TABLE as ART_4210_STAIRS_TABLE } from "./rules/art4210StairsTable.js";
export { ACCESSIBLE_RAMP_SLOPE_RULE } from "./dictionary/accessibility.js";
export { isAccessibleRamp, isAccessibleElevator } from "./engine/accessibleAlternatives.js";
export { determineStairRequirement } from "./engine/stairRequirement.js";
export { evaluateStairCompliance } from "./engine/evaluateStairCompliance.js";
export { runPreCheck, approximateStoreyCount } from "./precheck.js";
export type { PreCheckSeverity, PreCheckIssue, PreCheckResult } from "./precheck.js";
export type { Finding, FindingRuleId, FindingSeverity, FindingState, FindingBoundingBox } from "./types/finding.js";
